FROM node:16-alpine3.11 as build

ENV HOST 0.0.0.0

WORKDIR /usr/app/game
COPY game/package.json .

RUN npm set progress=false && \
    npm config set depth 0 && \
    npm install

COPY game/src /usr/app/game/src
COPY game/tsconfig.game.json /usr/app/game/tsconfig.game.json
COPY tsconfig.json /usr/app/tsconfig.json

COPY common /usr/app/common
WORKDIR /usr/app/common
RUN npm install

COPY @types /usr/app/@types
RUN npm run build-once


FROM node:16-alpine3.11 as release
RUN apk add mongodb-tools
WORKDIR /usr/app/game
COPY game/newrelic.js .

COPY --from=build /usr/app/common/dist /usr/app/common/dist
COPY --from=build /usr/app/common/node_modules /usr/app/common/node_modules
COPY --from=build /usr/app/game/dist /usr/app/game/dist
COPY --from=build /usr/app/game/node_modules /usr/app/game/node_modules
COPY game/package.json .

CMD ["npm", "run", "prod"]