FROM node:16-alpine3.11 as dependencies

ENV HOST 0.0.0.0

WORKDIR /usr/app/game
COPY game/package.json .

RUN npm set progress=false && \
    npm config set depth 0 && \
    npm install

COPY game/src /usr/app/game/src
COPY game/tsconfig.game.json /usr/app/game/tsconfig.game.json
COPY tsconfig.json /usr/app/tsconfig.json
COPY common /usr/app/common
COPY @types /usr/app/@types
RUN npm run build-once
COPY game/newrelic.js .
# FROM node:16-alpine3.11 as release
# WORKDIR /usr/app/game
# COPY --from=dependencies /usr/app/common /usr/app/common
# COPY --from=dependencies /usr/app/game/node_modules /usr/app/game/node_modules
# COPY --from=dependencies /usr/app/game/dist /usr/app/game/dist
# COPY game/package.json .

CMD ["npm", "run", "prod"]