import c from '../../../../../common/dist'

export const weapons: {
  [key in WeaponId]: BaseWeaponData
} = {
  tutorial1: {
    type: `weapon`,
    id: `tutorial1`,
    buyable: false,
    displayName: `Crustacean Cannon 1`,
    description: `Fires a two-pronged bolt of red energy at the target, somewhat resembling a crab's claw. Not suitable for large-scale combat, but enough to scare away some smaller threats.`,
    mass: 1000,
    basePrice: 0 * c.itemPriceMultiplier,
    range: 0.01,
    rarity: 9999999,
    reliability: 5,
    damage: 1.5,
    baseCooldown: 0.05 * 60 * 1000,
    maxHp: 10,
  },
  tiny1: {
    type: `weapon`,
    id: `tiny1`,
    displayName: `Squirt Gun`,
    description: `Ejects a short stream of hydrocarbons at a specified target. Deals little damage, so it's mostly useful for target practice.`,
    mass: 400,
    basePrice: 77 * c.itemPriceMultiplier,
    range: 0.075,
    rarity: 0.3,
    damage: 0.5,
    baseCooldown: 2 * 60 * 1000,
    maxHp: 2,
  },
  // cannons
  cannon1: {
    type: `weapon`,
    id: `cannon1`,
    displayName: `Crustacean Cannon 1`,
    description: `Fires a two-pronged bolt of red energy at the target, somewhat resembling a crab's claw. Not suitable for large-scale combat, but enough to scare away some smaller threats.`,
    mass: 1300,
    basePrice: 180 * c.itemPriceMultiplier,
    range: 0.15,
    rarity: 0.5,
    damage: 0.85,
    baseCooldown: 1 * 60 * 1000,
    maxHp: 3,
  },
  cannon2: {
    type: `weapon`,
    id: `cannon2`,
    displayName: `Crustacean Cannon 2`,
    description: `Fires a two-pronged bolt of red energy at the target, somewhat resembling a crab's claw. Not suitable for large-scale combat, but enough to scare away some smaller threats. The second entry in the series upgrades its range and damage.`,
    mass: 1400,
    basePrice: 230 * c.itemPriceMultiplier,
    range: 0.175,
    rarity: 2,
    damage: 1,
    baseCooldown: 1 * 60 * 1000,
    maxHp: 3,
  },
  cannon3: {
    type: `weapon`,
    id: `cannon3`,
    displayName: `Crustacean Cannon XD`,
    description: `Fires a two-pronged bolt of red energy at the target, somewhat resembling a crab's claw.`,
    mass: 1700,
    basePrice: 700 * c.itemPriceMultiplier,
    range: 0.22,
    rarity: 6,
    damage: 1.7,
    baseCooldown: 1 * 60 * 1000,
    maxHp: 3,
  },

  // snipers
  sniper1: {
    type: `weapon`,
    id: `sniper1`,
    displayName: `Monofang Harpoon`,
    description: `Able to shoot down targets from an impressive distance, the Harpoon class of weapons is feared by slow-moving craft who can't maneuver far enough from its reach.`,
    mass: 2400,
    basePrice: 1200 * c.itemPriceMultiplier,
    range: 0.25,
    rarity: 1.8,
    damage: 0.7,
    baseCooldown: 2 * 60 * 1000,
    maxHp: 2,
  },
  sniper2: {
    type: `weapon`,
    id: `sniper2`,
    displayName: `Bifang Harpoon`,
    description: `Able to shoot down targets from an impressive distance, the Harpoon class of weapons is feared by slow-moving craft who can't maneuver far enough from its reach.`,
    mass: 2700,
    basePrice: 2700 * c.itemPriceMultiplier,
    range: 0.3,
    rarity: 2.9,
    damage: 0.8,
    baseCooldown: 2.5 * 60 * 1000,
    maxHp: 2,
  },
  sniper3: {
    type: `weapon`,
    id: `sniper3`,
    displayName: `Trifang Harpoon`,
    description: `Able to shoot down targets from an impressive distance, the Harpoon class of weapons is feared by slow-moving craft who can't maneuver far enough from its reach.`,
    mass: 3000,
    basePrice: 2700 * c.itemPriceMultiplier,
    range: 0.35,
    rarity: 4.5,
    damage: 0.9,
    baseCooldown: 3 * 60 * 1000,
    maxHp: 2,
  },

  // sabers
  saber1: {
    type: `weapon`,
    id: `saber1`,
    displayName: `Swordfish Saber 1`,
    description: `Gets its name from its short range and relatively quick recharge time. Dueling ships wielding Swordfish Sabers have been known to perform fantastic dogfights around the moons of Osiris.`,
    mass: 2200,
    basePrice: 480 * c.itemPriceMultiplier,
    range: 0.05,
    rarity: 0.75,
    damage: 1.7,
    baseCooldown: 0.8 * 60 * 1000,
    maxHp: 4,
  },
  saber2: {
    type: `weapon`,
    id: `saber2`,
    displayName: `Swordfish Saber 2`,
    description: `Gets its name from its short range and relatively quick recharge time. Dueling ships wielding Swordfish Sabers have been known to perform fantastic dogfights around the moons of Osiris.`,
    mass: 2600,
    basePrice: 910 * c.itemPriceMultiplier,
    range: 0.055,
    rarity: 2,
    damage: 2,
    baseCooldown: 0.8 * 60 * 1000,
    maxHp: 4,
  },
  saber3: {
    type: `weapon`,
    id: `saber3`,
    displayName: `Swordfish Saber 3`,
    description: `Gets its name from its short range and relatively quick recharge time. Dueling ships wielding Swordfish Sabers have been known to perform fantastic dogfights around the moons of Osiris.`,
    mass: 2600,
    basePrice: 3100 * c.itemPriceMultiplier,
    range: 0.065,
    rarity: 4,
    damage: 2.3,
    baseCooldown: 0.7 * 60 * 1000,
    maxHp: 4,
  },
}
