version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      # Check for updates to node every weekday
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/game"
    schedule:
      # Check for updates to node every weekday
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/discord"
    schedule:
      # Check for updates to node every weekday
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      # Check for updates to node every weekday
      interval: "daily"
