FROM node:16-alpine3.11 as base

ENV HOST 0.0.0.0

WORKDIR /usr/app/frontend

COPY package.json .

FROM base AS dependencies
RUN npm install

FROM base as release
COPY --from=dependencies /usr/app/frontend/node_modules /usr/app/frontend/node_modules

ADD @types/ /usr/app/@types
ADD common/ /usr/app/common
ADD . /usr/app/frontend

RUN chown node:root /usr/app/frontend
RUN chmod -R 777 /usr/app/frontend/

CMD ["npm", "run", "dev"]
