FROM node:16-alpine3.11 as builder

WORKDIR /usr/app/frontend

COPY frontend/package*.json .
RUN npm install

COPY @types/ /usr/app/@types
COPY common/ /usr/app/common
COPY frontend .

RUN npm run build
RUN chown -R node:node /usr/app/frontend/.nuxt
RUN chmod -R 755 /usr/app/frontend/.nuxt

FROM node:16-alpine3.11 as release
WORKDIR /usr/app/frontend
ENV HOST 0.0.0.0
COPY --from=builder /usr/app/frontend/node_modules node_modules
COPY --from=builder /usr/app/frontend/.nuxt .nuxt

CMD ["npm", "run", "start"]
