version: '3.7'
services:
  mongodb:
    image: 'starfishgame/starfish-db:latest'
    restart: always
    volumes:
      - /mnt/disks/mongodb/db_data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: starfish
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
    secrets:
      - mongodb_root_username
      - mongodb_root_password
      - mongodb_username
      - mongodb_password
    logging:
      driver: loki

  game:
    image: 'starfishgame/starfish-game:latest'
    user: 'root'
    working_dir: /usr/app/game
    ports:
      - '4200:4200'
    command: 'npm run prod'
    environment:
      MONGODB_USERNAME_FILE: /run/secrets/mongodb_username
      MONGODB_PASSWORD_FILE: /run/secrets/mongodb_password
      ADMIN_KEYS_FILE: /run/secrets/admin_keys
    volumes:
      - /var/lib/nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - mongodb
    secrets:
      - mongodb_username
      - mongodb_password
      - admin_keys
    logging:
      driver: loki

  frontend:
    image: 'starfishgame/starfish-frontend:latest'
    user: 'node'
    working_dir: /usr/app/frontend
    ports:
      - '4300:4300'
    command: 'npm run start'
    secrets:
      - google_client_email
      - google_private_key
    logging:
      driver: loki

  discord:
    image: 'starfishgame/starfish-discord:latest'
    user: 'node'
    working_dir: /usr/app/discord
    command: 'npm run prod'
    secrets:
      - discord_token
      - bot_id
    logging:
      driver: loki

  nginx:
    image: 'starfishgame/starfish-nginx:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/lib/nginx/letsencrypt:/etc/letsencrypt
    logging:
      driver: loki

secrets:
  discord_token:
    file: discord/secrets/discord_token.txt
  bot_id:
    file: discord/secrets/bot_id.txt
  mongodb_username:
    file: db/secrets/mongodb_username.txt
  mongodb_password:
    file: db/secrets/mongodb_password.txt
  mongodb_root_username:
    file: db/secrets/mongodb_root_username.txt
  mongodb_root_password:
    file: db/secrets/mongodb_root_password.txt
  google_client_email:
    file: frontend/secrets/google_client_email.txt
  google_private_key:
    file: frontend/secrets/google_private_key.txt
  admin_keys:
    file: game/secrets/admin_keys.txt

volumes:
  db_data:
  letsencrypt:

networks:
  default:
