version: '3.7'
services:
  mongodb:
    image: 'xmadsen/starfish-db:prod-latest'
    restart: always
    volumes:
      - db_data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: starfish
      MONGO_INITDB_ROOT_USERNAME: mongodb_root_user
      MONGO_INITDB_ROOT_PASSWORD: mongodb_root_pass
    secrets:
      - mongodb_root_user
      - mongodb_root_pass

  mongo-express:
    image: 'mongo-express:0.54.0'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_AUTH_DATABASE: starfish
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongodb_root_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb_root_pass
      ME_CONFIG_BASICAUTH_USERNAME: mongodb_user
      ME_CONFIG_BASICAUTH_PASSWORD: mongodb_pass
    depends_on:
      - mongodb
    ports:
      - 8081:8081 
    secrets:
      - mongodb_user
      - mongodb_pass
      - mongodb_root_user
      - mongodb_root_pass

  game:
    image: 'xmadsen/starfish-game:prod-latest'
    user: 'node'
    working_dir: /usr/app/game
    ports:
      - '4200:4200'
    command: 'npm run dev'
    environment:
      MONGODB_ADMINUSERNAME: mongodb_user
      MONGODB_ADMINPASSWORD: mongodb_pass
    depends_on:
      - mongodb
    secrets:
      - mongodb_user
      - mongodb_pass

  frontend:
    image: 'xmadsen/starfish-frontend:prod-latest'
    user: 'node'
    working_dir: /usr/app/frontend
    ports:
      - '4300:4300'
    command: 'npm run dev'

  discord:
    image: 'xmadsen/starfish-discord:prod-latest'
    user: 'node'
    working_dir: /usr/app/discord
    command: 'npm run dev'
    secrets:
      - discord_token
      - bot_id

secrets:
  discord_token:
    file: discord/secrets/discord_token.txt
  bot_id:
    file: discord/secrets/bot_id.txt
  mongodb_user:  
    file: db/secrets/mongodb_user.txt
  mongodb_user:
    file: db/secrets/mongodb_pass.txt
  mongodb_pass:
    file: db/secrets/mongodb_root_user.txt
  mongodb_root_user:
    file: db/secrets/mongodb_root_user.txt
  mongodb_root_pass:
    file: db/secrets/mongodb_root_pass.txt
  
volumes:
  db_data:
