version: '3.7'
services:
  mongodb:
    image: 'mongo:4.0'
    restart: always
    volumes:
      - db_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: starfish
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    logging:
      driver: none

  mongo-express:
    image: 'mongo-express:0.54.0'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_AUTH_DATABASE: starfish
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_BASICAUTH_USERNAME: starfish
      ME_CONFIG_BASICAUTH_PASSWORD: starfish321
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    logging:
      driver: none
    secrets:
      - mongodb_root_username
      - mongodb_root_password
      - mongodb_username
      - mongodb_password

  game:
    # build: './game'
    image: 'xmadsen/starfish-game:prod-latest'
    user: 'node'
    working_dir: /usr/app/game
    ports:
      - '4200:4200'
    # expose:
    #   - '4200'
    volumes:
      - ./common:/usr/app/common
      - ./game/dist:/usr/app/game/dist
      - ./game/src:/usr/app/game/src
    command: 'npm run dev'
    # environment:
    #   MONGODB_ADMINUSERNAME: starfish
    #   MONGODB_ADMINPASSWORD: starfish123
    depends_on:
      - mongodb
    secrets:
      - mongodb_username
      - mongodb_password

  frontend:
    #build: './frontend'
    image: 'xmadsen/starfish-frontend:prod-latest'
    user: 'node'
    working_dir: /usr/app/frontend
    ports:
      - '4300:4300'
    volumes:
      - ./@types:/usr/app/@types
      - ./common:/usr/app/common
      - ./frontend:/usr/app/frontend/
    command: 'npm run dev'
    secrets:
      - google_client_email
      - google_private_key

  discord:
    #build: './discord'
    image: 'xmadsen/starfish-discord:prod-latest'
    user: 'node'
    working_dir: /usr/app/discord
    volumes:
      - ./common:/usr/app/common
      - ./discord/dist:/usr/app/discord/dist
      - ./discord/.env:/usr/app/discord/.env
    command: 'npm run dev'
    secrets:
      - discord_token
      - bot_id

  nginx:
    image: 'xmadsen/starfish-nginx:prod-latest'
    ports:
      - '80:80'

secrets:
  discord_token:
    file: discord/secrets/discord_token.txt
  bot_id:
    file: discord/secrets/bot_id.txt
  mongodb_username:
    file: db/secrets/mongodb_username.txt
  mongodb_password:
    file: db/secrets/mongodb_password.txt
  mongodb_root_username:
    file: db/secrets/mongodb_root_username.txt
  mongodb_root_password:
    file: db/secrets/mongodb_root_password.txt
  google_client_email:
    file: frontend/secrets/google_client_email.txt
  google_private_key:
    file: frontend/secrets/google_private_key.txt

volumes:
  db_data:
