version: '3.7'
services:
  mongodb:
    image: 'mongo:4.0'
    restart: always
    volumes:
      - db_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: starfish
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword

  game:
    image: 'starfishgame/starfish-game:pull-request-$PULL_REQUEST_NUMBER'
    user: 'node'
    working_dir: /usr/app/game
    ports:
      - 4200:4200
    volumes:
      - ./common:/usr/app/common
      - ./game/dist:/usr/app/game/dist
      - ./game/src:/usr/app/game/src
      - ./ssl:/usr/app/game/ssl
    command: 'npm run dev'
    depends_on:
      - mongodb
    environment:
      MONGODB_USERNAME_FILE: /run/secrets/mongodb_username
      MONGODB_PASSWORD_FILE: /run/secrets/mongodb_password
      ADMIN_KEYS_FILE: /run/secrets/admin_keys
    secrets:
      - mongodb_username
      - mongodb_password
      - admin_keys

  frontend:
    image: 'starfishgame/starfish-frontend:pull-request-$PULL_REQUEST_NUMBER'
    user: 'node'
    working_dir: /usr/app/frontend
    ports:
      - 4300:4300
    volumes:
      - ./@types:/usr/app/@types
      - ./common:/usr/app/common
      - ./frontend:/usr/app/frontend/
    command: 'npm run dev'
    secrets:
      - google_client_email
      - google_private_key

  discord:
    image: 'starfishgame/starfish-discord:pull-request-$PULL_REQUEST_NUMBER'
    user: 'node'
    working_dir: /usr/app/discord
    volumes:
      - ./common:/usr/app/common
      - ./discord/dist:/usr/app/discord/dist
      - ./discord/.env:/usr/app/discord/.env
    command: 'npm run dev'
    environment:
      BOT_ID_FILE: /run/secrets/bot_id
      DISCORD_TOKEN_FILE: /run/secrets/discord_token
    secrets:
      - discord_token
      - bot_id

  nginx:
    image: 'starfishgame/starfish-nginx:pull-request-$PULL_REQUEST_NUMBER'
    volumes:
      - ./ssl:/etc/nginx/self-signed-ssl
      - ./nginx/sites-enabled/default-test:/etc/nginx/sites-enabled/default
    ports:
      - '80:80'
      - '443:443'

secrets:
  discord_token:
    file: discord/secrets/discord_token.txt
  bot_id:
    file: discord/secrets/bot_id.txt
  mongodb_username:
    file: db/secrets/mongodb_testusername.txt
  mongodb_password:
    file: db/secrets/mongodb_testpassword.txt
  mongodb_root_username:
    file: db/secrets/mongodb_root_username.txt
  mongodb_root_password:
    file: db/secrets/mongodb_root_password.txt
  google_client_email:
    file: frontend/secrets/google_client_email.txt
  google_private_key:
    file: frontend/secrets/google_private_key.txt
  admin_keys:
    file: game/secrets/admin_keys.txt

volumes:
  db_data:

networks:
  default:
