version: '3.7'
services:
  mongodb:
    container_name: db
    image: 'mongo:4.0'
    restart: always
    volumes:
      - db_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: starfish
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword

  game:
    container_name: game
    image: 'starfishgame/starfish-game:ci-latest'
    user: 'root'
    working_dir: /usr/app/game
    ports:
      - 4200:4200
    volumes:
      - ./ssl:/usr/app/game/ssl
    command: 'npm run prod'
    depends_on:
      - mongodb
    environment:
      MONGODB_USERNAME_FILE: /run/secrets/mongodb_username
      MONGODB_PASSWORD_FILE: /run/secrets/mongodb_password
      ADMIN_KEYS_FILE: /run/secrets/admin_keys
      NODE_ENV: ci
    secrets:
      - mongodb_username
      - mongodb_password
      - admin_keys

  frontend:
    container_name: frontend
    image: 'starfishgame/starfish-frontend:ci-latest'
    user: 'node'
    working_dir: /usr/app/frontend
    ports:
      - 4300:4300
    command: 'npm run start'
    environment:
      IS_DOCKER: 'true'
      NODE_ENV: ci
    secrets:
      - google_client_email
      - google_private_key

  discord:
    container_name: discord
    image: 'starfishgame/starfish-discord:ci-latest'
    user: 'node'
    working_dir: /usr/app/discord
    command: 'npm run prod'
    environment:
      BOT_ID_FILE: /run/secrets/bot_id
      DISCORD_TOKEN_FILE: /run/secrets/discord_token
      NODE_ENV: ci
    secrets:
      - discord_token
      - bot_id

  nginx:
    container_name: nginx
    image: 'starfishgame/starfish-nginx:ci-latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./ssl:/etc/nginx/self-signed-ssl
      - ./nginx/sites-enabled/default-test:/etc/nginx/sites-enabled/default

secrets:
  discord_token:
    file: discord/secrets/discord_token.txt
  bot_id:
    file: discord/secrets/bot_id.txt
  mongodb_username:
    file: db/secrets/mongodb_testusername.txt
  mongodb_password:
    file: db/secrets/mongodb_testpassword.txt
  mongodb_root_username:
    file: db/secrets/mongodb_root_username.txt
  mongodb_root_password:
    file: db/secrets/mongodb_root_password.txt
  google_client_email:
    file: frontend/secrets/google_client_email.txt
  google_private_key:
    file: frontend/secrets/google_private_key.txt
  admin_keys:
    file: game/secrets/admin_keys.txt

volumes:
  db_data:

networks:
  default:
