version: '3.7'
services:
  mongodb:
    image: 'mongo:4.0'
    restart: always
    volumes:
      - db_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: spacecord
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    logging:
      driver: none

  mongo-express:
    image: 'mongo-express:0.54.0'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_AUTH_DATABASE: spacecord
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_BASICAUTH_USERNAME: spacecord
      ME_CONFIG_BASICAUTH_PASSWORD: spacecord321
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    logging:
      driver: none

  game:
    # build: './game'
    image: 'xmadsen/starfish-game:latest'
    user: 'node'
    working_dir: /usr/app/game
    ports:
      - '4200:4200'
    expose:
      - '4200'
    volumes:
      - ./common:/usr/app/common
      - ./game/dist:/usr/app/game/dist
      - ./game/src:/usr/app/game/src
    command: 'npm run dev'
    environment:
      MONGODB_ADMINUSERNAME: spacecord
      MONGODB_ADMINPASSWORD: spacecord123
    depends_on:
      - mongodb

  frontend:
    #build: './frontend'
    image: 'xmadsen/starfish-frontend:latest'
    user: 'node'
    working_dir: /usr/app/frontend
    ports:
      - '4300:4300'
    volumes:
      - ./@types:/usr/app/@types
      - ./common:/usr/app/common
      - ./frontend:/usr/app/frontend/
    command: 'npm run dev'

  discord:
    #build: './discord'
    image: 'xmadsen/starfish-discord:latest'
    user: 'node'
    working_dir: /usr/app/discord
    volumes:
      - ./common:/usr/app/common
      - ./discord/dist:/usr/app/discord/dist
      - ./discord/.env:/usr/app/discord/.env
    command: 'npm run dev'

volumes:
  db_data:
