import game from '../gameConstants'

export const armor: {
  [key in ArmorId]: BaseArmorData
} = {
  ai1: {
    type: `item`,
    buyable: false,
    itemType: `armor`,
    itemId: `ai1`,
    displayName: `Scaled Exoskeleton`,
    description: `Actually an organic growth on the outside of the ship, this rock-like shell will block a small amount of damage directed at your craft.`,
    mass: 1200 * game.itemMassMultiplier,
    rarity: 0.3,
    basePrice: { credits: 22 * game.itemPriceMultiplier },
    damageReduction: 0.2,
    maxHp: 3,
    maxLevel: 2,
  },

  starter1: {
    type: `item`,
    itemType: `armor`,
    itemId: `starter1`,
    displayName: `Scaled Exoskeleton`,
    description: `Actually an organic growth on the outside of the ship, this rock-like shell will block a small amount of damage directed at your craft.`,
    mass: 900 * game.itemMassMultiplier,
    rarity: 0.4,
    basePrice: { credits: 22 * game.itemPriceMultiplier },
    damageReduction: 0.1,
    maxHp: 7,
    maxLevel: 2,
    upgradableProperties: [`maxHp`],
  },
  starter2: {
    type: `item`,
    itemType: `armor`,
    itemId: `starter2`,
    displayName: `Grooved Exoskeleton`,
    description: `Actually an organic growth on the outside of the ship, this rock-like shell will block a small amount of damage directed at your craft. Grooves in the husk allow for some projectiles to glance off of the hull, diluting damage slightly more than a scaled armor.`,
    mass: 1000 * game.itemMassMultiplier,
    rarity: 0.5,
    basePrice: { credits: 55 * game.itemPriceMultiplier },
    damageReduction: 0.13,
    maxHp: 6.5,
    maxLevel: 2,
    upgradableProperties: [`damageReduction`, `maxHp`],
  },

  // block
  block1: {
    type: `item`,
    itemType: `armor`,
    itemId: `block1`,
    displayName: `Hardened Shell 01`,
    description: `Absorbs shockwaves effectively, as long as the armor doesn't crack.`,
    mass: 900 * game.itemMassMultiplier,
    rarity: 1,
    basePrice: { credits: 50 * game.itemPriceMultiplier },
    damageReduction: 0.35,
    maxHp: 4.5,
    maxLevel: 3,
    upgradableProperties: [`damageReduction`],
  },
  block2: {
    type: `item`,
    itemType: `armor`,
    itemId: `block2`,
    displayName: `Hardened Shell 02`,
    description: `Absorbs shockwaves effectively, as long as the armor doesn't crack.`,
    mass: 900 * game.itemMassMultiplier,
    rarity: 3.5,
    basePrice: { credits: 160 * game.itemPriceMultiplier },
    damageReduction: 0.4,
    maxHp: 5.9,
    maxLevel: 4,
    upgradableProperties: [`damageReduction`],
  },
  block3: {
    type: `item`,
    itemType: `armor`,
    itemId: `block3`,
    displayName: `Hardened Shell 03`,
    description: `Absorbs shockwaves effectively, as long as the armor doesn't crack.`,
    mass: 900 * game.itemMassMultiplier,
    rarity: 6,
    basePrice: { credits: 510 * game.itemPriceMultiplier },
    damageReduction: 0.45,
    maxHp: 6.8,
    maxLevel: 5,
    upgradableProperties: [`damageReduction`],
  },
  block4: {
    type: `item`,
    itemType: `armor`,
    itemId: `block4`,
    displayName: `Hardened Shell 04`,
    description: `Absorbs shockwaves effectively, as long as the armor doesn't crack.`,
    mass: 900 * game.itemMassMultiplier,
    rarity: 8,
    basePrice: { credits: 1090 * game.itemPriceMultiplier },
    damageReduction: 0.5,
    maxHp: 8.7,
    upgradableProperties: [`damageReduction`],
  },

  // tough
  tough1: {
    type: `item`,
    itemType: `armor`,
    itemId: `tough1`,
    displayName: `Blubber 10k`,
    description: `Relies on raw mass and thickness to absorb damage.`,
    mass: 1000 * game.itemMassMultiplier,
    rarity: 2,
    basePrice: { credits: 60 * game.itemPriceMultiplier },
    damageReduction: 0.05,
    maxHp: 10,
    maxLevel: 3,
    upgradableProperties: [`mass`, `maxHp`],
    upgradeBonus: 0.1,
  },
  tough2: {
    type: `item`,
    itemType: `armor`,
    itemId: `tough2`,
    displayName: `Blubber 20k`,
    description: `Relies on raw mass and thickness to absorb damage.`,
    mass: 1150 * game.itemMassMultiplier,
    rarity: 5,
    basePrice: { credits: 290 * game.itemPriceMultiplier },
    damageReduction: 0.05,
    maxHp: 12,
    maxLevel: 5,
    upgradableProperties: [`mass`, `maxHp`],
    upgradeBonus: 0.1,
  },
  tough3: {
    type: `item`,
    itemType: `armor`,
    itemId: `tough2`,
    displayName: `Blubber 30k`,
    description: `Relies on raw mass and thickness to absorb damage.`,
    mass: 1300 * game.itemMassMultiplier,
    rarity: 9,
    basePrice: { credits: 970 * game.itemPriceMultiplier },
    damageReduction: 0.05,
    maxHp: 14,
    maxLevel: 7,
    upgradableProperties: [`mass`, `maxHp`],
    upgradeBonus: 0.1,
  },
}
