import game from '../game'

export const chassis: {
  [key in ChassisId]: BaseChassisData
} = {
  starter1: {
    type: `chassis`,
    id: `starter1`,
    displayName: `Fishbowl 01`,
    description: `They say that a goldfish will grow to the size of its container. The goldfish in this bowl are feeling cramped, restrained to shallower waters.`,
    mass: 5000,
    basePrice: Number(game.itemPriceMultiplier),
    slots: 5,
    agility: 1.0,
    maxCargoSpace: 15,
    rarity: 0.5,
  },
  starter2: {
    type: `chassis`,
    id: `starter2`,
    displayName: `Fishbowl 02`,
    description: `They say that a goldfish will grow to the size of its container. The goldfish in this bowl are feeling cramped, restrained to shallower waters.`,
    mass: 5000,
    basePrice: 22 * game.itemPriceMultiplier,
    slots: 6,
    agility: 1.0,
    maxCargoSpace: 25,
    rarity: 1,
  },
  starter3: {
    // todo passives: somethin basic
    type: `chassis`,
    id: `starter3`,
    displayName: `Fishbowl 03`,
    description: `They say that a goldfish will grow to the size of its container. The goldfish in this bowl are feeling cramped, restrained to shallower waters.`,
    mass: 5000,
    basePrice: 45 * game.itemPriceMultiplier,
    slots: 6,
    agility: 1.0,
    maxCargoSpace: 30,
    rarity: 1.5,
  },
  fighter1: {
    // todo Passives may be related to damage-over-time (blood), or seeing attacks and their faction-colored trail on map from farther away,
    // (shark smells blood from far away)
    // Get a boost to damage if no allies are nearby
    type: `chassis`,
    id: `fighter1`,
    displayName: `Shark Tank v1`,
    description: `Space is your domain, and you are a lone hunter. Make your enemies bleed.`,
    mass: 4000,
    basePrice: 30 * game.itemPriceMultiplier,
    slots: 6,
    agility: 1.2,
    maxCargoSpace: 20,
    rarity: 1,
  },
  fighter2: {
    // todo Passives may be related to damage-over-time (blood), or seeing attacks and their faction-colored trail on map from farther away,
    // (shark smells blood from far away)
    // Get a boost to damage if no allies are nearby
    type: `chassis`,
    id: `fighter2`,
    displayName: `Shark Tank v2`,
    description: `Space is your domain, and you are a lone hunter. Make your enemies bleed. Now with a cool new passive: TODO`,
    mass: 4000,
    basePrice: 110 * game.itemPriceMultiplier,
    slots: 6,
    agility: 1.3,
    maxCargoSpace: 30,
    rarity: 2,
  },
  fighter3: {
    // todo Passives may be related to damage-over-time (blood), or seeing attacks and their faction-colored trail on map from farther away,
    // (shark smells blood from far away)
    // Get a boost to damage if no allies are nearby
    type: `chassis`,
    id: `fighter3`,
    displayName: `Shark Tank v3`,
    description: `Space is your domain, and you are a lone hunter. Make your enemies bleed. Now with cool new passives: TODO`,
    mass: 4000,
    basePrice: 110 * game.itemPriceMultiplier,
    slots: 7,
    agility: 1.35,
    maxCargoSpace: 40,
    rarity: 3,
  },

  // hauler
  hauler1: {
    type: `chassis`,
    id: `hauler1`,
    displayName: `Long Hauler 11`,
    description: `Made to serve aquatic life with migratory instincts. A bit cumbersome in a firefight, but allows for superior cargo space compared to other models in its price range.`,
    mass: 8000,
    basePrice: 50 * game.itemPriceMultiplier,
    slots: 6,
    agility: 0.7,
    maxCargoSpace: 50,
    rarity: 4,
  },
  hauler2: {
    type: `chassis`,
    id: `hauler2`,
    displayName: `Long Hauler 12`,
    description: `Made to serve aquatic life with migratory instincts. A bit cumbersome in a firefight, but allows for superior cargo space compared to other models in its price range.`,
    mass: 9600,
    basePrice: 160 * game.itemPriceMultiplier,
    slots: 6,
    agility: 0.75,
    maxCargoSpace: 60,
    rarity: 8,
  },
  hauler3: {
    type: `chassis`,
    id: `hauler3`,
    displayName: `Long Hauler 13`,
    description: `Made to serve aquatic life with migratory instincts. A bit cumbersome in a firefight, but allows for superior cargo space compared to other models in its price range.`,
    mass: 12600,
    basePrice: 300 * game.itemPriceMultiplier,
    slots: 7,
    agility: 0.75,
    maxCargoSpace: 80,
    rarity: 10,
  },

  // sailer
  sailer1: {
    type: `chassis`,
    id: `sailer1`,
    displayName: `Swift Sailer mk.1`,
    description: `Exceptionally light and nimble, this craft excels at getting from A to B quickly.`,
    mass: 2000,
    basePrice: 52 * game.itemPriceMultiplier,
    slots: 5,
    agility: 1.4,
    maxCargoSpace: 20,
    rarity: 4,
  },
  sailer2: {
    type: `chassis`,
    id: `sailer2`,
    displayName: `Swift Sailer mk.2`,
    description: `Exceptionally light and nimble, this craft excels at getting from A to B quickly.`,
    mass: 2100,
    basePrice: 130 * game.itemPriceMultiplier,
    slots: 6,
    agility: 1.45,
    maxCargoSpace: 30,
    rarity: 7,
  },
  sailer3: {
    type: `chassis`,
    id: `sailer3`,
    displayName: `Swift Sailer mk.3`,
    description: `Exceptionally light and nimble, this craft excels at getting from A to B quickly.`,
    mass: 2100,
    basePrice: 220 * game.itemPriceMultiplier,
    slots: 6,
    agility: 1.5,
    maxCargoSpace: 40,
    rarity: 10,
  },

  // mega
  mega1: {
    type: `chassis`,
    id: `mega1`,
    displayName: `Whale Pod 01`,
    description: `Size over agility, age over beauty.`,
    mass: 60000,
    basePrice: 710 * game.itemPriceMultiplier,
    slots: 15,
    agility: 0.45,
    maxCargoSpace: 300,
    rarity: 12,
  },
  mega2: {
    type: `chassis`,
    id: `mega2`,
    displayName: `Whale Pod 02`,
    description: `Size over agility, age over beauty. The second iteration adds EVEN MORE slots and cargo space, at the cost of even more agility.`,
    mass: 70000,
    basePrice: 970 * game.itemPriceMultiplier,
    slots: 18,
    agility: 0.35,
    maxCargoSpace: 400,
    rarity: 18,
  },
  mega3: {
    type: `chassis`,
    id: `mega3`,
    displayName: `Whale Pod 03`,
    description: `Size over agility, age over beauty. The third iteration adds EVEN MORE slots and cargo space, at the cost of even more agility.`,
    mass: 95000,
    basePrice: 970 * game.itemPriceMultiplier,
    slots: 21,
    agility: 0.25,
    maxCargoSpace: 500,
    rarity: 25,
  },
}
