import game from '../gameConstants'

export const engines: {
  [key in EngineId]: BaseEngineData
} = {
  tutorial1: {
    buyable: false,
    special: true,
    type: `engine`,
    id: `tutorial1`,
    displayName: `Bubble Booster v1`,
    description: `Expels repeated payloads of hyrdocarbon-based fuel that explode outside of the ship, forming a trail that looks not unlike bubbles. A highly inefficient form of propulsion.`,
    mass: 100 * game.itemMassMultiplier,
    basePrice: { credits: 0 * game.itemPriceMultiplier },
    rarity: 999999,
    // manualThrustMultiplier: 10,
    passiveThrustMultiplier: 400,
    maxHp: 10,
    passives: [],
  },
  tiny1: {
    buyable: false,
    type: `engine`,
    id: `tiny1`,
    displayName: `Flappotron`,
    description: `Uses repeated inertial motion to very slowly shift the ship's position.`,
    mass: 2000 * game.itemMassMultiplier,
    basePrice: { credits: 0 * game.itemPriceMultiplier },
    rarity: 0.5,
    passiveThrustMultiplier: 0.5,
    maxHp: 2,
    passives: [],
  },
  ai1: {
    buyable: false,
    type: `engine`,
    id: `ai1`,
    displayName: `Thermal Cruiser 001`,
    description: `Mostly useful for gradual coasting, this engine relies on catching radiation from nearby stars to convert into thrust.`,
    mass: 2000 * game.itemMassMultiplier,
    basePrice: { credits: 0 * game.itemPriceMultiplier },
    rarity: 1,
    passiveThrustMultiplier: 1.2,
    maxHp: 2,
    passives: [],
  },
  starter1: {
    type: `engine`,
    id: `starter1`,
    displayName: `Bubble Booster v1`,
    description: `Expels repeated payloads of hyrdocarbon-based fuel that explode outside of the ship, forming a trail that looks not unlike bubbles. A highly inefficient form of propulsion.`,
    mass: 600 * game.itemMassMultiplier,
    basePrice: { credits: 17 * game.itemPriceMultiplier },
    rarity: 0.4,
    passiveThrustMultiplier: 0.7,
    maxHp: 5,
    repairDifficulty: 0.9,
    passives: [
      {
        id: `boostBrake`,
        intensity: 0.1,
      },
    ],
  },
  starter2: {
    type: `engine`,
    id: `starter2`,
    displayName: `Bubble Booster v2`,
    description: `Expels repeated payloads of hyrdocarbon-based fuel that explode outside of the ship, forming a trail that looks not unlike bubbles. A highly inefficient form of propulsion. Version two slightly improves upon the chemical formula used in the fuel.`,
    mass: 800 * game.itemMassMultiplier,
    basePrice: { credits: 21 * game.itemPriceMultiplier },
    rarity: 1,
    passiveThrustMultiplier: 0.8,
    maxHp: 5,
    repairDifficulty: 0.85,
    passives: [
      {
        id: `boostBrake`,
        intensity: 0.1,
      },
    ],
  },
  starter3: {
    type: `engine`,
    id: `starter3`,
    displayName: `Bubble Booster v3`,
    description: `Expels repeated payloads of hyrdocarbon-based fuel that explode outside of the ship, forming a trail that looks not unlike bubbles. A highly inefficient form of propulsion. Version three further improves upon the chemical formula used in the fuel.`,
    mass: 1000 * game.itemMassMultiplier,
    basePrice: { credits: 49 * game.itemPriceMultiplier },
    rarity: 1.5,
    passiveThrustMultiplier: 0.9,
    maxHp: 5,
    repairDifficulty: 0.8,
    passives: [
      {
        id: `boostBrake`,
        intensity: 0.1,
      },
    ],
  },

  // basic
  basic1: {
    type: `engine`,
    id: `basic1`,
    displayName: `Tail Thruster 100`,
    description: `Gains velocity through an oscillating power flux located at the rear of the ship.`,
    mass: 900 * game.itemMassMultiplier,
    basePrice: { credits: 80 * game.itemPriceMultiplier },
    rarity: 2,
    passiveThrustMultiplier: 1.2,
    maxHp: 4,
    passives: [
      {
        id: `boostBrake`,
        intensity: 0.05,
      },
    ],
  },
  basic2: {
    type: `engine`,
    id: `basic2`,
    displayName: `Tail Thruster 200`,
    description: `Gains velocity through an oscillating power flux located at the rear of the ship.`,
    mass: 1200 * game.itemMassMultiplier,
    basePrice: { credits: 190 * game.itemPriceMultiplier },
    rarity: 6,
    passiveThrustMultiplier: 1.4,
    maxHp: 4,
    passives: [
      {
        id: `boostBrake`,
        intensity: 0.075,
      },
    ],
  },
  basic3: {
    type: `engine`,
    id: `basic3`,
    displayName: `Tail Thruster 300`,
    description: `Gains velocity through an oscillating power flux located at the rear of the ship.`,
    mass: 1500 * game.itemMassMultiplier,
    basePrice: { credits: 350 * game.itemPriceMultiplier },
    rarity: 7,
    passiveThrustMultiplier: 1.6,
    maxHp: 4,
    passives: [
      {
        id: `boostBrake`,
        intensity: 0.1,
      },
    ],
  },

  // duo
  duo1: {
    type: `engine`,
    id: `duo1`,
    displayName: `HydroCarbonator v1`,
    description: `The fusion of hydrocarbons provides for a healthy passive baseline of power, along with the ability to overload the reactor for short bursts of speed.`,
    mass: 900 * game.itemMassMultiplier,
    basePrice: { credits: 80 * game.itemPriceMultiplier },
    rarity: 3,
    passiveThrustMultiplier: 0.4,
    manualThrustMultiplier: 0.4,
    maxHp: 3,
  },
  duo2: {
    type: `engine`,
    id: `duo2`,
    displayName: `HydroCarbonator v2`,
    description: `The fusion of hydrocarbons provides for a healthy passive baseline of power, along with the ability to overload the reactor for short bursts of speed.`,
    mass: 1200 * game.itemMassMultiplier,
    basePrice: { credits: 190 * game.itemPriceMultiplier },
    rarity: 6,
    passiveThrustMultiplier: 0.4,
    manualThrustMultiplier: 0.5,
    maxHp: 3,
  },
  duo3: {
    type: `engine`,
    id: `duo3`,
    displayName: `HydroCarbonator v3`,
    description: `The fusion of hydrocarbons provides for a healthy passive baseline of power, along with the ability to overload the reactor for short bursts of speed.`,
    mass: 1500 * game.itemMassMultiplier,
    basePrice: { credits: 350 * game.itemPriceMultiplier },
    rarity: 7,
    passiveThrustMultiplier: 0.4,
    manualThrustMultiplier: 0.6,
    maxHp: 3,
  },

  // glass
  glass1: {
    type: `engine`,
    id: `glass1`,
    displayName: `Gossamer Fin mk.1`,
    description: `An ultraviolet fin extends gloriously from the ship. As swift and as vulnerable as it is beautiful.`,
    mass: 100 * game.itemMassMultiplier,
    basePrice: { credits: 210 * game.itemPriceMultiplier },
    rarity: 5,
    manualThrustMultiplier: 1.7,
    reliability: 0.3,
    maxHp: 1,
    repairDifficulty: 1.2,
    passives: [
      { id: `boostChassisAgility`, intensity: 0.03 },
    ],
  },
  glass2: {
    type: `engine`,
    id: `glass2`,
    displayName: `Gossamer Fin mk.2`,
    description: `An ultraviolet fin extends gloriously from the ship. As swift and as vulnerable as it is beautiful.`,
    mass: 100 * game.itemMassMultiplier,
    basePrice: { credits: 690 * game.itemPriceMultiplier },
    rarity: 9,
    manualThrustMultiplier: 2,
    reliability: 0.4,
    maxHp: 1,
    repairDifficulty: 1.2,
    passives: [
      { id: `boostChassisAgility`, intensity: 0.06 },
    ],
  },
  glass3: {
    type: `engine`,
    id: `glass3`,
    displayName: `Gossamer Fin mk.3`,
    description: `An ultraviolet fin extends gloriously from the ship. As swift and as vulnerable as it is beautiful.`,
    mass: 100 * game.itemMassMultiplier,
    basePrice: { credits: 1770 * game.itemPriceMultiplier },
    rarity: 12,
    manualThrustMultiplier: 2.3,
    reliability: 0.5,
    maxHp: 1,
    repairDifficulty: 1.2,
    passives: [
      { id: `boostChassisAgility`, intensity: 0.1 },
    ],
  },

  // heavy
  heavy1: {
    type: `engine`,
    id: `heavy1`,
    displayName: `Big Fin`,
    description: `Big fin. Fin big.`,
    mass: 1400 * game.itemMassMultiplier,
    basePrice: { credits: 70 * game.itemPriceMultiplier },
    rarity: 5,
    manualThrustMultiplier: 1.1,
    reliability: 3,
    maxHp: 6,
    repairDifficulty: 0.8,
  },
  heavy2: {
    type: `engine`,
    id: `heavy2`,
    displayName: `Bigger Fin`,
    description: `Big fin. Fin big.`,
    mass: 1400 * game.itemMassMultiplier,
    basePrice: { credits: 230 * game.itemPriceMultiplier },
    rarity: 9,
    manualThrustMultiplier: 1.2,
    reliability: 4,
    maxHp: 7,
    repairDifficulty: 0.8,
  },
  heavy3: {
    type: `engine`,
    id: `heavy3`,
    displayName: `Even Bigger Fin`,
    description: `Big fin. Fin big.`,
    mass: 1400 * game.itemMassMultiplier,
    basePrice: { credits: 600 * game.itemPriceMultiplier },
    rarity: 12,
    manualThrustMultiplier: 1.3,
    reliability: 5,
    maxHp: 8,
    repairDifficulty: 0.8,
  },
}
