# 1st stage - install dependencies
FROM node:16-alpine3.11 as builder
WORKDIR /usr/app/discord
COPY discord/package*.json .
RUN npm install


# 2nd stage - compile typescript
FROM builder as npm
WORKDIR /usr/app/common
COPY common .
RUN npm install

WORKDIR /usr/app/discord
COPY @types /usr/app/@types
COPY discord .
COPY tsconfig.json /usr/app/tsconfig.json
# COPY discord/tsconfig.discord.json ./tsconfig.discord.json
# COPY discord/package*.json .
# RUN npm install --production
RUN npm run buildprod

FROM node:16-alpine3.11
WORKDIR /usr/app/discord
COPY --from=npm /usr/app/discord/dist ./dist
COPY --from=npm /usr/app/discord/package.json ./package.json
COPY --from=npm /usr/app/discord/node_modules ./node_modules

RUN mkdir /usr/app/common
COPY --from=npm common/dist /usr/app/common/dist
COPY --from=npm common/node_modules /usr/app/common/node_modules
COPY @types /usr/app/@types


CMD ["npm", "run", "prod"]