FROM nginx:1.21-alpine
RUN apk add python3 python3-dev py3-pip build-base libressl-dev musl-dev libffi-dev cargo openssl-dev gcc

COPY nginx/nginx-prod.conf /etc/nginx/nginx.conf
COPY nginx/docker-entrypoint.sh /etc/nginx/docker-entrypoint.sh

# install certbot
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -y | sh
RUN pip3 install --upgrade pip
RUN pip3 install wheel
RUN pip3 install cryptography
RUN pip3 install certbot-nginx
RUN mkdir /etc/letsencrypt
# RUN apk add python3-certbot-nginx
# RUN add-apt-repository ppa:certbot/certbot
# RUN apt-get update -y
# RUN apt-get install -y certbot python-certbot-nginx

# deamon mode off
# RUN echo "\ndaemon off;" >> /etc/nginx/nginx.conf

# expose ports
EXPOSE 80 443

# add nginx live conf
ADD nginx/starfish.conf /etc/nginx/sites-available/starfish.cool

# create symlinks
RUN mkdir /etc/nginx/sites-enabled
RUN ln -s /etc/nginx/sites-available/starfish.cool /etc/nginx/sites-enabled/starfish

# make certs dir as volume
VOLUME ["/etc/letsencrypt"]

ENTRYPOINT [ "/etc/nginx/docker-entrypoint.sh" ]