FROM nginx:1.21.5-alpine
RUN apk add python3 python3-dev py3-pip build-base libressl-dev musl-dev libffi-dev cargo openssl-dev gcc
# install certbot
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -y | sh
RUN pip3 install --upgrade pip
RUN pip3 install wheel
RUN pip3 install cryptography
RUN pip3 install certbot-nginx
RUN mkdir /etc/letsencrypt

# expose ports
EXPOSE 80 443

COPY nginx/nginx-prod.conf /etc/nginx/nginx.conf

RUN echo "0 23 * * * certbot renew" | crontab -