<template>
  <Box class="cockpit">
    <template #title
      ><span class="sectionemoji">🛫</span>Cockpit</template
    >
    <div class="panesection">
      <!-- <div class="panesubhead">Target destination</div>
      <div>
        {{
          crewMember.targetLocation
            ? crewMember.targetLocation.map(
                (tl) => Math.round(tl * 10000) / 10000,
              )
            : 'none'
        }}
      </div> -->
      <div class="sub">
        Click on the map or a button below to set your
        target destination.
      </div>
    </div>

    <div
      class="panesection"
      v-if="
        ship.visible.ships.length ||
          planetsToShow.length ||
          ship.visible.caches.length
      "
    >
      <div>
        <div class="panesubhead">Move Toward</div>
      </div>

      <span
        v-for="planet in planetsToShow"
        :key="'gotoplanet' + planet.name"
      >
        <button
          @click="setTarget(planet.location)"
          :class="{
            secondary:
              !crewMember.targetLocation ||
              planet.location[0] !==
                crewMember.targetLocation[0] ||
              planet.location[1] !==
                crewMember.targetLocation[1],
          }"
        >
          <span :style="{ color: planet.color }"
            >🪐{{ planet.name }}</span
          >
        </button> </span
      ><span
        v-for="otherShip in ship.visible.ships"
        :key="'gotoship' + otherShip.id"
      >
        <button
          @click="setTarget(otherShip.location)"
          :class="{
            secondary:
              !crewMember.targetLocation ||
              otherShip.location[0] !==
                crewMember.targetLocation[0] ||
              otherShip.location[1] !==
                crewMember.targetLocation[1],
          }"
        >
          🚀{{ otherShip.name }}
        </button> </span
      ><span
        v-for="cache in cachesToShow"
        :key="'gotocache' + cache.location"
      >
        <button
          @click="setTarget(cache.location)"
          :class="{
            secondary:
              !crewMember.targetLocation ||
              cache.location[0] !==
                crewMember.targetLocation[0] ||
              cache.location[1] !==
                crewMember.targetLocation[1],
          }"
        >
          📦Cache (<AngleArrow :angle="cache.angle" />
          {{ Math.round(cache.distance * 1000) / 1000 }}AU)
        </button>
      </span>
    </div>

    <div class="panesection">
      <div class="panesubhead">Thrust</div>
      <div>
        Active engine{{
          activeEngines.length === 1 ? '' : 's'
        }}: {{ activeEngines.length }}
      </div>
      <div>
        Thrust amplification from engines:
        {{
          Math.round(engineThrustAmplification * 100) / 100
        }}x
      </div>
      <div>
        Speed generated by you: ~{{
          Math.round(memberThrust * 60 * 60 * 100) / 100
        }}
        AU/hour
      </div>
    </div>
  </Box>
</template>

<script lang="ts">
import c from '../../../../common/src'
import { mapState } from 'vuex'
interface ComponentShape {
  [key: string]: any
}

export default {
  data(): ComponentShape {
    return { c }
  },
  computed: {
    ...mapState(['ship', 'crewMember']),
    planetsToShow(this: ComponentShape) {
      const p = [...(this.ship.visible.planets || [])]
      for (let seen of this.ship.seenPlanets) {
        if (!p.find((pl) => pl.name === seen.name))
          p.push(seen)
      }
      return p
    },
    activeEngines(this: ComponentShape) {
      return (
        this.ship?.engines.filter(
          (e: EngineStub) => (e.repair || 0) > 0,
        ) || []
      )
    },
    engineThrustAmplification(this: ComponentShape) {
      return this.activeEngines.reduce(
        (total: number, e: EngineStub) =>
          total +
          (e.thrustAmplification || 0) * (e.repair || 0),
        0,
      )
    },
    pilotingSkill(this: ComponentShape) {
      return (
        this.crewMember.skills.find(
          (s: XPData) => s.skill === 'piloting',
        )?.level || 1
      )
    },
    memberThrust(this: ComponentShape) {
      return c.getThrustMagnitudeForSingleCrewMember(
        this.pilotingSkill,
        this.engineThrustAmplification,
      )
    },
    cachesToShow(this: ComponentShape) {
      return this.ship?.visible.caches
        .map((cache: CacheStub) => ({
          ...cache,
          distance: c.distance(
            this.ship.location,
            cache.location,
          ),
          angle: c.angleFromAToB(
            this.ship.location,
            cache.location,
          ),
        }))
        .sort((a: any, b: any) => a.distance - b.distance)
    },
  },
  watch: {},
  mounted(this: ComponentShape) {},
  methods: {
    setTarget(
      this: ComponentShape,
      target: CoordinatePair,
    ) {
      this.$store.commit('setTarget', target)
    },
  },
}
</script>

<style lang="scss" scoped>
.cockpit {
  position: relative;
  width: 300px;
}
</style>
