<template>
  <Box class="cockpit">
    <template #title
      ><span class="sectionemoji">🛫</span>Cockpit</template
    >
    <div class="panesection">
      <div class="panesubhead">Target destination</div>
      <div>
        {{
          crewMember.targetLocation
            ? crewMember.targetLocation.map(
                (tl) => Math.round(tl * 10000) / 10000,
              )
            : 'none'
        }}
      </div>
    </div>

    <div class="panesection" v-if="planetsToShow.length">
      <div class="panesubhead">Move Toward Planet</div>
      <div
        v-for="planet in planetsToShow"
        :key="'gotoplanet' + planet.name"
      >
        <button @click="setTarget(planet.location)">
          🪐{{ planet.name }} ({{ planet.location }})
        </button>
      </div>
    </div>

    <div
      class="panesection"
      v-if="ship.visible.ships.length"
    >
      <div class="panesubhead">Move Toward Ship</div>
      <div
        v-for="otherShip in ship.visible.ships"
        :key="'gotoship' + otherShip.id"
      >
        <button @click="setTarget(otherShip.location)">
          🚀{{ otherShip.name }} ({{ otherShip.location }})
        </button>
      </div>
    </div>

    <div
      class="panesection"
      v-if="ship.visible.caches.length"
    >
      <div class="panesubhead">Move Toward Cache</div>
      <div
        v-for="cache in ship.visible.caches"
        :key="'gotocache' + Math.random()"
      >
        <button @click="setTarget(cache.location)">
          📦Cache at {{ cache.location }}
        </button>
      </div>
    </div>

    <div class="panesection">
      <div class="panesubhead">Thrust</div>
      <div>
        Active engine{{
          activeEngines.length === 1 ? '' : 's'
        }}: {{ activeEngines.length }}
      </div>
      <div>
        Thrust amplification from engines:
        {{ engineThrustAmplification }}x
      </div>
      <div>
        Speed generated by you:
        {{
          Math.round(memberThrust * 60 * 60 * 10000) / 10000
        }}
        AU/hour
      </div>
    </div>
  </Box>
</template>

<script lang="ts">
import c from '../../../../common/src'
import { mapState } from 'vuex'
interface ComponentShape {
  [key: string]: any
}

export default {
  data(): ComponentShape {
    return { c }
  },
  computed: {
    ...mapState(['ship', 'crewMember']),
    planetsToShow(this: ComponentShape) {
      const p = [...(this.ship.visible.planets || [])]
      for (let seen of this.ship.seenPlanets) {
        if (!p.find((pl) => pl.name === seen.name))
          p.push(seen)
      }
      return p
    },
    activeEngines(this: ComponentShape) {
      return (
        this.ship?.engines.filter(
          (e: EngineStub) => e.repair > 0,
        ) || []
      )
    },
    engineThrustAmplification(this: ComponentShape) {
      return this.activeEngines.reduce(
        (total: number, e: EngineStub) =>
          total + (e.thrustAmplification || 0),
        0,
      )
    },
    pilotingSkill(this: ComponentShape) {
      return (
        this.crewMember.skills.find(
          (s: XPData) => s.skill === 'piloting',
        )?.level || 1
      )
    },
    memberThrust(this: ComponentShape) {
      return c.getThrustMagnitudeForSingleCrewMember(
        this.pilotingSkill,
        this.engineThrustAmplification,
      )
    },
  },
  watch: {},
  mounted(this: ComponentShape) {},
  methods: {
    setTarget(
      this: ComponentShape,
      target: CoordinatePair,
    ) {
      this.$store.commit('setTarget', target)
    },
  },
}
</script>

<style lang="scss" scoped>
.cockpit {
  position: relative;
  width: 300px;
}
</style>
