name: Build and push Docker images
on:
  pull_request:
    branches:
      - '*'
jobs:
  docker-build-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: db/Dockerfile-prod
            image: 'starfish-db'
            folder: 'db'
          - dockerfile: game/Dockerfile-prod
            image: 'starfish-game'
            folder: 'game'
          - dockerfile: discord/Dockerfile-prod
            image: 'starfish-discord'
            folder: 'discord'
          - dockerfile: frontend/Dockerfile-prod
            image: 'starfish-frontend'
            folder: 'frontend'
          - dockerfile: nginx/Dockerfile-prod
            image: 'starfish-nginx'
            folder: 'nginx'

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - '${{matrix.folder}}/**'
              - common/**

      - name: Build and push Docker images
        uses: whoan/docker-build-with-cache-action@v5
        if: steps.changes.outputs.src == 'true'
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          context: .
          dockerfile: ${{ matrix.dockerfile }}
          image_name: starfishgame/${{ matrix.image }}
          image_tag: pull-request-${{ github.event.number }}
          push_git_tag: true
