name: Starfish Build check

on:
  pull_request:
    branches:
      - '*'
jobs:
  npm-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - folder: 'game'

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Run tests on ${{matrix.folder}}
        run: npm run test
        working-directory: ${{matrix.folder}}

  docker:
    needs: npm-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: db/Dockerfile-prod
            image: 'starfish-db'
            folder: 'db'
          - dockerfile: game/Dockerfile-prod
            image: 'starfish-game'
            folder: 'game'
          - dockerfile: discord/Dockerfile-prod
            image: 'starfish-discord'
            folder: 'discord'
          - dockerfile: frontend/Dockerfile-prod
            image: 'starfish-frontend'
            folder: 'frontend'
          - dockerfile: nginx/Dockerfile-prod
            image: 'starfish-nginx'
            folder: 'nginx'
          - dockerfile: prometheus/Dockerfile-prod
            image: 'starfish-prometheus'
            folder: 'prometheus'

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.dockerfile }}
          context: .
          push: false
          tags: starfishgame/${{ matrix.image }}:latest, starfishgame/${{ matrix.image }}:${{ github.run_number }}
          cache-from: type=gha
