name: 'Push to production'
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.dockerfile }}
          context: .
          push: true
          tags: starfishgame/${{ matrix.image }}:latest,starfishgame/${{ matrix.image }}:${{ github.run_number }}
          cache-from: type=gha

  update-prod:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest images to host VM and restart containers
        uses: garygrossgarten/github-action-ssh@v0.6.4
        id: produp
        with:
          command: |
            cd starfish;
            git pull;
            docker-compose -f docker-compose-prod.yml pull
            docker-compose -f docker-compose-prod.yml up -d
            docker image prune -f
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME}}
          privateKey: ${{ secrets.HOST_PRIVATE_KEY}}

      - name: Notify if something went wrong
        if: steps.produp.outcome == 'failure'
        uses: sebastianpopp/discord-action@releases/v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: 'Something went wrong when we tried to bring up production.'
