name: Starfish build/push

on:
  push:
    branches:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - dockerfile: db/Dockerfile-prod
           image: "starfish-db"
         - dockerfile: game/Dockerfile-prod
           image: "starfish-game"
         - dockerfile: discord/Dockerfile-prod
           image: "starfish-discord"
         - dockerfile: frontend/Dockerfile-prod
           image: "starfish-frontend"
         - dockerfile: nginx/Dockerfile-prod
           image: "starfish-nginx"

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Generate tags
        id: docker_tags
        uses: dnaka91/action-docker-tags@v0.1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1


      - uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.dockerfile }}
          context: .
          push: true
          tags: ${{ steps.docker_tags.outputs.tags  + steps.buildnumber.outputs.build_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}





