name: Starfish build/push

on:
  push:
    branches:
      - '*'
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: db/Dockerfile-prod
            image: 'starfish-db'
            folder: 'db'
          - dockerfile: game/Dockerfile-prod
            image: 'starfish-game'
            folder: 'game'
          - dockerfile: discord/Dockerfile-prod
            image: 'starfish-discord'
            folder: 'discord'
          - dockerfile: frontend/Dockerfile-prod
            image: 'starfish-frontend'
            folder: 'frontend'
          - dockerfile: nginx/Dockerfile-prod
            image: 'starfish-nginx'
            folder: 'nginx'
          - dockerfile: prometheus/Dockerfile-prod
            image: 'starfish-prometheus'
            folder: 'prometheus'

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - '${{matrix.folder}}/**'
              - common/**

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images and push to Dockerhub
        if: steps.changes.outputs.src == 'true'
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.dockerfile }}
          context: .
          push: true
          tags: starfishgame/${{ matrix.image }}:latest, starfishgame/${{ matrix.image }}:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  prod-check:
    needs: docker
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"

      - name: Pull latest images to host VM and restart containers
        uses: garygrossgarten/github-action-ssh@v0.6.4
        with:
          command: |
            cd starfish;
            git pull;
            docker-compose -f docker-compose-prod.yml pull
            docker-compose -f docker-compose-prod.yml up -d
            docker image prune -f
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME}}
          privateKey: ${{ secrets.HOST_PRIVATE_KEY}}

      - name: Notify if something went wrong
        if: steps.1.outcome == 'failure'
        uses: sebastianpopp/discord-action@releases/v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: '#48f442'
          username: 'GitHub Monitor'
          message: 'Something went wrong when we tried to bring up production. Here's the error message:${{steps.1.outputs}}'
