 steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push db
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: db/Dockerfile-prod
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/starfish-db:latest
      
      - name: Build and push game
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: game/Dockerfile-prod
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/starfish-game:latest
      
      - name: Build and push frontend
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: frontend/Dockerfile-prod
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/starfish-frontend:latest

      - name: Build and push discord
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: discord/Dockerfile-prod
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/starfish-discord:latest

        
      - name: Build and push nginx
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: nginx/Dockerfile-prod
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/starfish-nginx:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}





