name: 'Test Report'
on:
  workflow_run:
    workflows: ['Pull Request']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Download test result artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pull-request-workflow.yml
          name: test-results

      - uses: dorny/test-reporter@v1
        with:
          name: Mocha Test Results # Name of the check run which will be created
          path: 'test-results.json' # Path to test results (inside artifact .zip)
          reporter: mocha-json
